### ISSUE TITLE
Any benefit to falling back to rAF?

### ISSUE THREAD

**Issue by s3ththompson** [choojs/on-idle#11]
IIUC Safari doesn't support requestIdleCallback, but they do support requestAnimationFrame. Would the latter be a better fallback than `setTimeout(cb, 0)`?

**Comment by yoshuawuyts** [comment]
Heya, interesting question! Sooo, the short version is: not really!

It mostly doesn't matter, because both `RAF` and `setTimeout` will resolve sometime in the next frame. I tend to usually only call `RAF` if there's work available that needs painting on the screen, and `setTimeout()` for things that don't require painting.

Because `requestIdleCallback` cannot do anything that requires painting (yay, blocking repaints!) - I tend to just use `setTimeout(cb, 0)`.

But yeah, there's not really a difference haha.

**Comment by s3ththompson** [comment]
Fascinating, thanks for the background!
